services:
  service:
    build:
      context: .
    ports:
      - 8080:8080
    container_name: employee-details
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/employee_test
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Bhavs@66
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'mysql'
    ports:
      - 3306:3306
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=Bhavs@66
      - MYSQL_DATABASE=employee_test